version: "3.7"

services:
  henry-steam-api:
    # network_mode: bridge
    image: henry-steam-api
    build: ./
    environment:
      # GUNICORN
      - HENRY_STEAM_API_PYTHON_PORT=5000

      # LOGS
      - NIVEL_LOGS=INFO
      - DIRECTORIO_LOGS=logs/

      # APP
      - POOL_SIZE_DEFAULT=50
      - MAX_OVERFLOW_DEFAULT=100
      - DIRECTORY_FILES=files/
      - HENRY_STEAM_API_ENVIRONMENT_MODE=development

    restart: always
    volumes:
      - ./logs:/usr/src/logs
      - ./files:/usr/src/files
      
    ports:
      - 5000:5000
